CREATE TYPE "Role" AS ENUM ('REQUESTER','TECHNICIAN','MANAGER','ADMIN');
CREATE TYPE "TicketStatus" AS ENUM ('OPEN','IN_PROGRESS','WAITING','RESOLVED','CLOSED','CANCELLED');
CREATE TYPE "Priority" AS ENUM ('LOW','MEDIUM','HIGH','CRITICAL');
CREATE TABLE "Department" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Department_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Department_name_key" ON "Department"("name");
CREATE TABLE "Category" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Category_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Category_name_key" ON "Category"("name");
CREATE TABLE "Sla" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"priority" "Priority" NOT NULL,"responseMins" INTEGER NOT NULL,"resolutionMins" INTEGER NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,CONSTRAINT "Sla_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Sla_name_key" ON "Sla"("name"); CREATE UNIQUE INDEX "Sla_priority_key" ON "Sla"("priority");
CREATE TABLE "User" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"email" TEXT NOT NULL,"passwordHash" TEXT NOT NULL,"role" "Role" NOT NULL DEFAULT 'REQUESTER',"active" BOOLEAN NOT NULL DEFAULT true,"departmentId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "User_email_key" ON "User"("email"); CREATE INDEX "User_role_active_idx" ON "User"("role","active"); CREATE INDEX "User_departmentId_idx" ON "User"("departmentId");
CREATE TABLE "Ticket" ("id" TEXT NOT NULL,"number" SERIAL NOT NULL,"subject" TEXT NOT NULL,"description" TEXT NOT NULL,"status" "TicketStatus" NOT NULL DEFAULT 'OPEN',"priority" "Priority" NOT NULL DEFAULT 'MEDIUM',"requesterId" TEXT NOT NULL,"assigneeId" TEXT,"departmentId" TEXT NOT NULL,"categoryId" TEXT,"slaId" TEXT,"dueAt" TIMESTAMP(3),"resolvedAt" TIMESTAMP(3),"closedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Ticket_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Ticket_number_key" ON "Ticket"("number"); CREATE INDEX "Ticket_status_priority_idx" ON "Ticket"("status","priority"); CREATE INDEX "Ticket_requesterId_createdAt_idx" ON "Ticket"("requesterId","createdAt"); CREATE INDEX "Ticket_assigneeId_status_idx" ON "Ticket"("assigneeId","status"); CREATE INDEX "Ticket_departmentId_status_idx" ON "Ticket"("departmentId","status");
CREATE TABLE "TicketMessage" ("id" TEXT NOT NULL,"ticketId" TEXT NOT NULL,"authorId" TEXT NOT NULL,"body" TEXT NOT NULL,"internal" BOOLEAN NOT NULL DEFAULT false,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "TicketMessage_pkey" PRIMARY KEY ("id"));
CREATE INDEX "TicketMessage_ticketId_createdAt_idx" ON "TicketMessage"("ticketId","createdAt");
CREATE TABLE "TicketAttachment" ("id" TEXT NOT NULL,"ticketId" TEXT NOT NULL,"name" TEXT NOT NULL,"url" TEXT NOT NULL,"size" INTEGER,"mimeType" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "TicketAttachment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Asset" ("id" TEXT NOT NULL,"tag" TEXT NOT NULL,"name" TEXT NOT NULL,"type" TEXT NOT NULL,"serialNumber" TEXT,"location" TEXT,"status" TEXT NOT NULL DEFAULT 'ATIVO',"notes" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "Asset_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "Asset_tag_key" ON "Asset"("tag"); CREATE INDEX "Asset_type_status_idx" ON "Asset"("type","status");
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL,"userId" TEXT,"action" TEXT NOT NULL,"entity" TEXT NOT NULL,"entityId" TEXT,"details" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id"));
CREATE INDEX "AuditLog_createdAt_idx" ON "AuditLog"("createdAt"); CREATE INDEX "AuditLog_entity_entityId_idx" ON "AuditLog"("entity","entityId");
ALTER TABLE "User" ADD CONSTRAINT "User_departmentId_fkey" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Ticket" ADD CONSTRAINT "Ticket_requesterId_fkey" FOREIGN KEY ("requesterId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Ticket" ADD CONSTRAINT "Ticket_assigneeId_fkey" FOREIGN KEY ("assigneeId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Ticket" ADD CONSTRAINT "Ticket_departmentId_fkey" FOREIGN KEY ("departmentId") REFERENCES "Department"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Ticket" ADD CONSTRAINT "Ticket_categoryId_fkey" FOREIGN KEY ("categoryId") REFERENCES "Category"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Ticket" ADD CONSTRAINT "Ticket_slaId_fkey" FOREIGN KEY ("slaId") REFERENCES "Sla"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "TicketMessage" ADD CONSTRAINT "TicketMessage_ticketId_fkey" FOREIGN KEY ("ticketId") REFERENCES "Ticket"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "TicketMessage" ADD CONSTRAINT "TicketMessage_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "TicketAttachment" ADD CONSTRAINT "TicketAttachment_ticketId_fkey" FOREIGN KEY ("ticketId") REFERENCES "Ticket"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
