services:
  db:
    image: postgres:16-alpine
    container_name: ti-service-desk-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ti_service_desk
      POSTGRES_USER: ti_admin
      POSTGRES_PASSWORD: troque-esta-senha
    ports:
      - "5432:5432"
    volumes:
      - ti_service_desk_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ti_admin -d ti_service_desk"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  ti_service_desk_pgdata:
